/**
 * Core type definitions for the occtwasm WASM module.
 *
 * Provides the OcctModule interface (Emscripten module shape),
 * initialization options, and cast helper function types matching
 * the functions exposed by cast_helpers.cpp.
 */

import type {
  GeneratedOcctModule,
  EmbindHandles,
} from '../../generated/ts/module-types.js';

export type {
  EmbindHandles,
  EmbindConstructors,
  EmbindEnums,
  GeneratedOcctModule,
} from '../../generated/ts/module-types.js';

// ---------------------------------------------------------------------------
// Manual helper function types (from manual C++ embind helpers)
// ---------------------------------------------------------------------------

interface ManualHelperFunctions {
  // --- Arc helpers (arc_helpers.cpp) ---
  MakeArcEdge3d(p1: EmbindHandles.gp_Pnt, p2: EmbindHandles.gp_Pnt, p3: EmbindHandles.gp_Pnt): EmbindHandles.TopoDS_Edge;
  MakeArcEdge2d(p1: EmbindHandles.gp_Pnt2d, p2: EmbindHandles.gp_Pnt2d, p3: EmbindHandles.gp_Pnt2d): EmbindHandles.TopoDS_Edge;

  // --- Curve measurement helpers (curve_measure_helpers.cpp) ---
  EdgeLength(edge: EmbindHandles.TopoDS_Edge): number;
  WireLength(wire: EmbindHandles.TopoDS_Wire): number;
  PointAtLengthOnEdge(edge: EmbindHandles.TopoDS_Edge, length: number): EmbindHandles.gp_Pnt;
  PointAtLengthOnWire(wire: EmbindHandles.TopoDS_Wire, length: number): EmbindHandles.gp_Pnt;

  // --- GProp helpers (gprop_helpers.cpp) ---
  BRepGProp_LinearProperties(shape: EmbindHandles.TopoDS_Shape): GPropGPropsHandle;
  BRepGProp_SurfaceProperties(shape: EmbindHandles.TopoDS_Shape): GPropGPropsHandle;
  BRepGProp_VolumeProperties(shape: EmbindHandles.TopoDS_Shape): GPropGPropsHandle;

  // --- Mesh helpers (mesh_helpers.cpp) ---
  MeshShape(shape: EmbindHandles.TopoDS_Shape, deflection: number, angle: number): any;

  // --- BSpline helpers (bspline_helpers.cpp) ---
  MakeBSplineCurveEdge(poles: any, knots: any, mults: any, degree: number): EmbindHandles.TopoDS_Edge;
  MakeBSplineSurfaceFace(poles: any, uKnots: any, vKnots: any, uMults: any, vMults: any, uDeg: number, vDeg: number, nUPoles: number, nVPoles: number): EmbindHandles.TopoDS_Face;

  // --- Curve info helpers (curve_info_helpers.cpp) ---
  GetEdgeBSplineInfo(edge: EmbindHandles.TopoDS_Edge): any;

  // --- Export helpers (export_helpers.cpp) ---
  ExportBRep(shape: EmbindHandles.TopoDS_Shape): string;

  // --- STEP export helpers (step_export_helpers.cpp) ---
  ExportSTEP(shape: EmbindHandles.TopoDS_Shape): string;
}

// ---------------------------------------------------------------------------
// Manual embind handle types (not generated by codegen)
// ---------------------------------------------------------------------------

/** GProp_GProps raw handle — bound manually in gprop_helpers.cpp */
export interface GPropGPropsHandle {
  Mass(): number;
  CentreOfMass(): EmbindHandles.gp_Pnt;
  MatrixOfInertia(): EmbindHandles.gp_Mat;
  delete(): void;
}

/** BRepAlgoAPI_Section raw handle — bound manually in boolean_helpers.cpp */
export interface BRepAlgoAPISectionHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepOffsetAPI_ThruSections raw handle — bound manually in loft_helpers.cpp */
export interface BRepOffsetAPIThruSectionsHandle {
  AddWire(wire: EmbindHandles.TopoDS_Wire): void;
  AddVertex(vertex: EmbindHandles.TopoDS_Vertex): void;
  CheckCompatibility(check: boolean): void;
  SetSmoothing(useSmoothing: boolean): void;
  SetMaxDegree(maxDegree: number): void;
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  FirstShape(): EmbindHandles.TopoDS_Shape;
  LastShape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepPrimAPI_MakeBox raw handle — bound manually in primitive_helpers.cpp */
export interface BRepPrimAPIMakeBoxHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  Solid(): EmbindHandles.TopoDS_Solid;
  delete(): void;
}

/** BRepPrimAPI_MakeCylinder raw handle — bound manually in primitive_helpers.cpp */
export interface BRepPrimAPIMakeCylinderHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepPrimAPI_MakeSphere raw handle — bound manually in primitive_helpers.cpp */
export interface BRepPrimAPIMakeSphereHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepBuilderAPI_MakeFace raw handle — bound manually in face_helpers.cpp */
export interface BRepBuilderAPIMakeFaceHandle {
  IsDone(): boolean;
  Face(): EmbindHandles.TopoDS_Face;
  Shape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepAlgoAPI_Fuse raw handle — bound manually in boolean_ops_helpers.cpp */
export interface BRepAlgoAPIFuseHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepAlgoAPI_Cut raw handle — bound manually in boolean_ops_helpers.cpp */
export interface BRepAlgoAPICutHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepAlgoAPI_Common raw handle — bound manually in boolean_ops_helpers.cpp */
export interface BRepAlgoAPICommonHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepOffsetAPI_MakePipe raw handle — bound manually in pipe_helpers.cpp */
export interface BRepOffsetAPIMakePipeHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  FirstShape(): EmbindHandles.TopoDS_Shape;
  LastShape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

interface ManualEmbindClasses {
  GProp_GProps: { new(): GPropGPropsHandle };
  BRepAlgoAPI_Section: {
    FromShapes(s1: EmbindHandles.TopoDS_Shape, s2: EmbindHandles.TopoDS_Shape): BRepAlgoAPISectionHandle;
    FromShapePlane(shape: EmbindHandles.TopoDS_Shape, pln: EmbindHandles.gp_Pln): BRepAlgoAPISectionHandle;
  };
  BRepOffsetAPI_ThruSections: {
    new(isSolid: boolean, isRuled: boolean): BRepOffsetAPIThruSectionsHandle;
  };
  BRepPrimAPI_MakeBox: {
    FromCornerAndSize(p: EmbindHandles.gp_Pnt, dx: number, dy: number, dz: number): BRepPrimAPIMakeBoxHandle;
    FromTwoCorners(p1: EmbindHandles.gp_Pnt, p2: EmbindHandles.gp_Pnt): BRepPrimAPIMakeBoxHandle;
  };
  BRepPrimAPI_MakeCylinder: {
    FromAx2(axes: EmbindHandles.gp_Ax2, R: number, H: number): BRepPrimAPIMakeCylinderHandle;
    FromAx2Angle(axes: EmbindHandles.gp_Ax2, R: number, H: number, angle: number): BRepPrimAPIMakeCylinderHandle;
  };
  BRepPrimAPI_MakeSphere: {
    FromCenterRadius(center: EmbindHandles.gp_Pnt, R: number): BRepPrimAPIMakeSphereHandle;
  };
  BRepBuilderAPI_MakeFace: {
    FromWire(wire: EmbindHandles.TopoDS_Wire, onlyPlane: boolean): BRepBuilderAPIMakeFaceHandle;
    FromPlane(pln: EmbindHandles.gp_Pln): BRepBuilderAPIMakeFaceHandle;
    FromPlaneAndBounds(pln: EmbindHandles.gp_Pln, uMin: number, uMax: number, vMin: number, vMax: number): BRepBuilderAPIMakeFaceHandle;
  };
  BRepAlgoAPI_Fuse: {
    Create(s1: EmbindHandles.TopoDS_Shape, s2: EmbindHandles.TopoDS_Shape): BRepAlgoAPIFuseHandle;
  };
  BRepAlgoAPI_Cut: {
    Create(s1: EmbindHandles.TopoDS_Shape, s2: EmbindHandles.TopoDS_Shape): BRepAlgoAPICutHandle;
  };
  BRepAlgoAPI_Common: {
    Create(s1: EmbindHandles.TopoDS_Shape, s2: EmbindHandles.TopoDS_Shape): BRepAlgoAPICommonHandle;
  };
  BRepOffsetAPI_MakePipe: {
    new(spine: EmbindHandles.TopoDS_Wire, profile: EmbindHandles.TopoDS_Shape): BRepOffsetAPIMakePipeHandle;
  };
}

// ---------------------------------------------------------------------------
// Emscripten WASM module
// ---------------------------------------------------------------------------

/** Initialized Emscripten WASM module produced by createOCCTModule(). */
export interface OcctModule extends GeneratedOcctModule, ManualHelperFunctions, ManualEmbindClasses {
  // --- Standard Emscripten heap views ---
  HEAP8: Int8Array;
  HEAP16: Int16Array;
  HEAP32: Int32Array;
  HEAPU8: Uint8Array;
  HEAPU16: Uint16Array;
  HEAPU32: Uint32Array;
  HEAPF32: Float32Array;
  HEAPF64: Float64Array;

  // --- Memory management ---
  _malloc(size: number): number;
  _free(ptr: number): void;

  // --- Runtime state ---
  calledRun: boolean;

  // --- Cast helpers (from cast_helpers.cpp) ---
  TopoDS_ToVertex: CastHelper;
  TopoDS_ToEdge: CastHelper;
  TopoDS_ToWire: CastHelper;
  TopoDS_ToFace: CastHelper;
  TopoDS_ToShell: CastHelper;
  TopoDS_ToSolid: CastHelper;
  TopoDS_ToCompSolid: CastHelper;
  TopoDS_ToCompound: CastHelper;

  /**
   * Index signature for any additional embind-registered entities
   * not yet explicitly typed.
   */
  [key: string]: any;
}

// ---------------------------------------------------------------------------
// Initialization
// ---------------------------------------------------------------------------

/** Options passed to createOCCTModule(). */
export interface InitOptions {
  /** Custom resolver for the .wasm file location. */
  locateFile?: (path: string, scriptDirectory: string) => string;
  /** Custom URL for the occt.js glue script. Overrides the default resolution. */
  wasmJsUrl?: string;
}

// ---------------------------------------------------------------------------
// Cast helper signature
// ---------------------------------------------------------------------------

/**
 * Function type for the TopoDS_To* cast helpers.
 *
 * Each helper takes a raw embind handle representing a TopoDS_Shape and
 * returns a raw embind handle for the specific subtype (Vertex, Edge, etc.).
 */
export type CastHelper = (shape: any) => any;
