/**
 * Core type definitions for the occtwasm WASM module.
 *
 * Provides the OcctModule interface (Emscripten module shape),
 * initialization options, and cast helper function types matching
 * the functions exposed by cast_helpers.cpp.
 */

import type {
  GeneratedOcctModule,
  EmbindHandles,
} from '../../generated/ts/module-types.js';

export type {
  EmbindHandles,
  EmbindConstructors,
  EmbindEnums,
  GeneratedOcctModule,
} from '../../generated/ts/module-types.js';

// ---------------------------------------------------------------------------
// Manual helper function types (from manual C++ embind helpers)
// ---------------------------------------------------------------------------

interface ManualHelperFunctions {
  // --- Arc helpers (arc_helpers.cpp) ---
  MakeArcEdge3d(p1: EmbindHandles.gp_Pnt, p2: EmbindHandles.gp_Pnt, p3: EmbindHandles.gp_Pnt): EmbindHandles.TopoDS_Edge;
  MakeArcEdge2d(p1: EmbindHandles.gp_Pnt2d, p2: EmbindHandles.gp_Pnt2d, p3: EmbindHandles.gp_Pnt2d): EmbindHandles.TopoDS_Edge;

  // --- Curve measurement helpers (curve_measure_helpers.cpp) ---
  EdgeLength(edge: EmbindHandles.TopoDS_Edge): number;
  WireLength(wire: EmbindHandles.TopoDS_Wire): number;
  PointAtLengthOnEdge(edge: EmbindHandles.TopoDS_Edge, length: number): EmbindHandles.gp_Pnt;
  PointAtLengthOnWire(wire: EmbindHandles.TopoDS_Wire, length: number): EmbindHandles.gp_Pnt;

  // --- GProp helpers (gprop_helpers.cpp) ---
  BRepGProp_LinearProperties(shape: EmbindHandles.TopoDS_Shape): GPropGPropsHandle;
  BRepGProp_SurfaceProperties(shape: EmbindHandles.TopoDS_Shape): GPropGPropsHandle;
  BRepGProp_VolumeProperties(shape: EmbindHandles.TopoDS_Shape): GPropGPropsHandle;
}

// ---------------------------------------------------------------------------
// Manual embind handle types (not generated by codegen)
// ---------------------------------------------------------------------------

/** GProp_GProps raw handle — bound manually in gprop_helpers.cpp */
export interface GPropGPropsHandle {
  Mass(): number;
  CentreOfMass(): EmbindHandles.gp_Pnt;
  MatrixOfInertia(): EmbindHandles.gp_Mat;
  delete(): void;
}

/** BRepAlgoAPI_Section raw handle — bound manually in boolean_helpers.cpp */
export interface BRepAlgoAPISectionHandle {
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

/** BRepOffsetAPI_ThruSections raw handle — bound manually in loft_helpers.cpp */
export interface BRepOffsetAPIThruSectionsHandle {
  AddWire(wire: EmbindHandles.TopoDS_Wire): void;
  AddVertex(vertex: EmbindHandles.TopoDS_Vertex): void;
  CheckCompatibility(check: boolean): void;
  SetSmoothing(useSmoothing: boolean): void;
  SetMaxDegree(maxDegree: number): void;
  Build(): void;
  IsDone(): boolean;
  Shape(): EmbindHandles.TopoDS_Shape;
  FirstShape(): EmbindHandles.TopoDS_Shape;
  LastShape(): EmbindHandles.TopoDS_Shape;
  delete(): void;
}

interface ManualEmbindClasses {
  GProp_GProps: { new(): GPropGPropsHandle };
  BRepAlgoAPI_Section: {
    FromShapes(s1: EmbindHandles.TopoDS_Shape, s2: EmbindHandles.TopoDS_Shape): BRepAlgoAPISectionHandle;
    FromShapePlane(shape: EmbindHandles.TopoDS_Shape, pln: EmbindHandles.gp_Pln): BRepAlgoAPISectionHandle;
  };
  BRepOffsetAPI_ThruSections: {
    new(isSolid: boolean, isRuled: boolean): BRepOffsetAPIThruSectionsHandle;
  };
}

// ---------------------------------------------------------------------------
// Emscripten WASM module
// ---------------------------------------------------------------------------

/** Initialized Emscripten WASM module produced by createOCCTModule(). */
export interface OcctModule extends GeneratedOcctModule, ManualHelperFunctions, ManualEmbindClasses {
  // --- Standard Emscripten heap views ---
  HEAP8: Int8Array;
  HEAP16: Int16Array;
  HEAP32: Int32Array;
  HEAPU8: Uint8Array;
  HEAPU16: Uint16Array;
  HEAPU32: Uint32Array;
  HEAPF32: Float32Array;
  HEAPF64: Float64Array;

  // --- Memory management ---
  _malloc(size: number): number;
  _free(ptr: number): void;

  // --- Runtime state ---
  calledRun: boolean;

  // --- Cast helpers (from cast_helpers.cpp) ---
  TopoDS_ToVertex: CastHelper;
  TopoDS_ToEdge: CastHelper;
  TopoDS_ToWire: CastHelper;
  TopoDS_ToFace: CastHelper;
  TopoDS_ToShell: CastHelper;
  TopoDS_ToSolid: CastHelper;
  TopoDS_ToCompSolid: CastHelper;
  TopoDS_ToCompound: CastHelper;

  /**
   * Index signature for any additional embind-registered entities
   * not yet explicitly typed.
   */
  [key: string]: any;
}

// ---------------------------------------------------------------------------
// Initialization
// ---------------------------------------------------------------------------

/** Options passed to createOCCTModule(). */
export interface InitOptions {
  /** Custom resolver for the .wasm file location. */
  locateFile?: (path: string, scriptDirectory: string) => string;
}

// ---------------------------------------------------------------------------
// Cast helper signature
// ---------------------------------------------------------------------------

/**
 * Function type for the TopoDS_To* cast helpers.
 *
 * Each helper takes a raw embind handle representing a TopoDS_Shape and
 * returns a raw embind handle for the specific subtype (Vertex, Edge, etc.).
 */
export type CastHelper = (shape: any) => any;
